app/views/pages/dashboard/index.liquid
app/views/pages/profile/index.liquid
app/views/partials/theme/simple/profile/private_feed.liquid

It was showing all products, created by anyone, on profile page.

Profile: fix showing user products

---

app/views/partials/lib/commands/sessions/store_profile_in_session.liquid
app/views/partials/theme/simple/layout/header.liquid

I guess we could store just the tiny version URL for now but it seems to me that we might be using the other version as well in other places so it would be more future-proof to store the whole object in session.

Added default profile picture to session information

---

app/views/partials/theme/simple/posts/card.liquid
app/views/partials/theme/simple/posts/vote_box.liquid
test/helper.js
test/marketplace_modern_test.js
test/pages/topicsPage.js

check errors includes liquid errors, translation missing, and it checks if page exists (404)

Errors check

---

app/graphql/posts/search.graphql
app/views/pages/posts/index.liquid
app/views/partials/lib/queries/posts/search.liquid
app/views/partials/theme/simple/posts/card.liquid

https://trello.com/c/sujXG7g5/223-questions-module-bugs

Questions: filter by tag

---

app/views/pages/dashboard/posts/accept.liquid
app/views/pages/dashboard/posts/delete.liquid
app/views/pages/dashboard/posts/edit.liquid
app/views/pages/dashboard/posts/update.liquid
app/views/partials/lib/queries/posts/find.liquid

https://trello.com/c/sujXG7g5/223-questions-module-bugs

Questions: allow edit and delete only your own questions

---

app/translations/en.yml
app/views/pages/dashboard/posts/delete.liquid
app/views/partials/theme/simple/dashboard/posts/index.liquid
app/views/partials/theme/simple/dashboard/posts/reply.liquid
app/views/partials/theme/simple/posts/card.liquid
app/views/partials/theme/simple/posts/index.liquid
app/views/partials/theme/simple/profile/card.liquid
src/js/markdown-editor.js
src/js/photo-upload.js

https://trello.com/c/sujXG7g5/223-questions-module-bugs

Questions: fixes - edit own post, default avatar

---

app/views/pages/profile/index.liquid
app/views/partials/lib/queries/activities/items/audience.liquid
app/views/partials/lib/queries/activities/model.liquid
app/views/partials/lib/queries/activities/users/audience.liquid
app/views/partials/lib/queries/metrics/find.liquid
app/views/partials/lib/queries/profiles/find.liquid
app/views/partials/lib/queries/relationships/find.liquid
app/views/partials/theme/simple/quick_search/index.liquid
modules/chat/public/views/pages/inbox.html.liquid
modules/chat/public/views/partials/channels/conversate.html.liquid
modules/chat/public/views/partials/inbox/conversations.liquid
modules/chat/public/views/partials/message_button.liquid
modules/chat/public/views/partials/theme/json/messages/show.liquid

extension to previous script from #93 
```
$ find . -type f -name "*.liquid" -print0 | xargs -0 sed -i 's/models\.results/records.results/g'
$ find . -type f -name "*.liquid" -print0 | xargs -0 sed -i 's/models\.has_previous_page/records.has_previous_page/g'
$ find . -type f -name "*.liquid" -print0 | xargs -0 sed -i 's/models\.has_next_page/records.has_next_page/g'
```

rename-models-to-records part 2

---

app/views/partials/theme/simple/layout/header.liquid

fix problem with default avatar assign to uncompleted profiles

fix problem with default avatar assign to uncompleted profiles

---

app/views/pages/api/photos/create.json.liquid
app/views/pages/dashboard/profile/update.liquid

- fix uploading avatar on signup
- fix setting avater in top menu

fix-updating-avatar

---

app/views/pages/dashboard/posts/create.liquid
app/views/pages/dashboard/posts/edit.liquid
app/views/pages/dashboard/posts/edit_answer.liquid
app/views/pages/dashboard/posts/new.liquid
app/views/pages/dashboard/posts/update.liquid
app/views/pages/posts/show.liquid
app/views/partials/theme/simple/dashboard/posts/edit.liquid
app/views/partials/theme/simple/dashboard/posts/form.liquid
app/views/partials/theme/simple/dashboard/posts/new.liquid
app/views/partials/theme/simple/dashboard/posts/reply.liquid
app/views/partials/theme/simple/photos/s3_form.liquid
app/views/partials/theme/simple/posts/show.liquid
src/js/markdown-editor.js

https://trello.com/c/8u1kPu8n/56-there-is-no-way-of-uploading-images-from-the-editor-while-it-might-be-a-core-functionality

Questions: upload images

---

app/graphql/posts/search.graphql
app/views/partials/theme/simple/posts/card.liquid

https://trello.com/c/ljvlAshy/40-as-a-user-i-would-like-to-delete-my-answer

Questions: delete your answers

---

app/graphql/models/search.graphql
app/translations/en.yml
app/views/partials/f_link_to.liquid
app/views/partials/theme/simple/layout/header.liquid

Fixes: https://trello.com/c/fmBK4ge0/36-as-a-user-i-would-like-to-find-a-questions-using-search

Fix search for questions

---

app/graphql/posts/search.graphql

https://trello.com/c/D16TfYGI/85-the-tag-search-returns-all-the-tags-that-include-given-string

Questions: search tags by exact match

---

app/assets/images/logo.svg
app/views/layouts/application.html.liquid
app/views/partials/theme/simple/items/show.liquid
app/views/partials/theme/simple/layout/header.liquid
app/views/partials/theme/simple/posts/metatags.liquid
app/views/partials/theme/simple/posts/show.liquid

https://trello.com/c/2F9TtfS8/60-open-graph-tags-og-tags-set-for-all-dynamic-pages

Questions: add metatags

---

app/translations/en.yml
app/views/partials/theme/simple/posts/vote_box.liquid

Fixes: https://trello.com/c/uHNRn1pt/74-improve-ux-for-voting-counter

Questions: improve ux for votes

---

app/graphql/posts/search.graphql
app/views/pages/dashboard/posts/update.liquid
app/views/partials/lib/commands/posts/cache_score.liquid
app/views/partials/lib/commands/posts/create/build.liquid
app/views/partials/lib/commands/posts/update/build.liquid
app/views/partials/lib/consumers/post_updated/cache_calcualte.liquid
app/views/partials/lib/consumers/post_voted/cache_calculate.liquid

https://trello.com/c/6mInAdsN/87-sort-answers-by-score-createdat-instead-of-just-createdat

Sort answers by score

---

app/views/pages/dashboard/posts/vote.liquid

Fixes: https://trello.com/c/VpcGcCux/88-self-question-upvoting-redirects-to-dashboard

Questions: fix error page when you cant vote

---

app/views/partials/theme/simple/activities/feed_unit/header.liquid
app/views/partials/theme/simple/admin/index.liquid
app/views/partials/theme/simple/admin/items/index.liquid
app/views/partials/theme/simple/admin/users/index.liquid
app/views/partials/theme/simple/dashboard/items/index.liquid
app/views/partials/theme/simple/dashboard/orders/index.liquid
app/views/partials/theme/simple/statuses/index.liquid
modules/chat/public/views/partials/inbox/conversation.liquid

Fixes: https://trello.com/c/JkTCu1ii/13-unify-date-format

Change date format to compact everywhere

---

app/migrations/20201214135248_posts_fill_uuid.liquid

Fixes: https://trello.com/c/OeFK2OKL/107-ive-tried-to-add-a-comment-and-got-an-error

Fix migration for filling uuids in posts

---

app/views/partials/lib/commands/posts/create/check.liquid
app/views/partials/lib/commands/posts/update/check.liquid

https://trello.com/c/xQn6E1Mq/42-limit-question-title-character-count

Questions: limit title length

---

app/graphql/posts/tags.graphql
app/views/pages/api/posts/tags.json.liquid
app/views/partials/lib/queries/posts/tags.liquid
app/views/partials/theme/simple/dashboard/posts/form.liquid
package-lock.json
package.json
src/js/apiFetch.js
src/js/app.js
src/js/markdown-editor.js
src/js/photo-upload.js
src/js/tags-input.js
test/pages/topicsPage.js

Fixes:
https://trello.com/c/VvEaPZBI/71-as-a-user-i-would-like-to-know-how-tags-are-separated
https://trello.com/c/hAcEyjBQ/120-tags-are-saved-with-spaces-in-them-thus-they-cannot-be-searched-after

Questions: use js plugin to enter and autocomplete tags

---

app/views/partials/lib/commands/sessions/store_profile_in_session.liquid

potential fix for too big session objects [?]

fix-user-session-with-long-avatar-paths

---

app/views/pages/style-guide.html.liquid
app/views/partials/theme/simple/dashboard/posts/index.liquid
app/views/partials/theme/simple/ui/tags.liquid
src/css/components/button.css
test/marketplace_modern_test.js
test/pages/topicsPage.js

Currently a single update for this one layout. I was trying to create a partial that would build those tables but we have quite a variety of content here and I found using it uncomfortable so I guess I will be replacing the other tables layout and generator manually according to the designs. At least for now.

Layout dashboard questions

---

app/views/partials/theme/simple/dashboard/posts/edit_answer.liquid
app/views/partials/theme/simple/dashboard/posts/form.liquid
app/views/partials/theme/simple/dashboard/posts/reply.liquid

https://trello.com/c/2DZpsXeq/132-cant-add-more-images-in-case-when-i-want-to-edit-my-answer

Questions: fix uploading images when editing answer

---

app/translations/en.yml

regarding to this card https://trello.com/c/xQfq6VJS/258-translation-issue

add translations for questions in template

---

app/views/partials/lib/profile_present_or_redirect.liquid
package.json
src/js/tags-input.js
test/fixtures.js
test/marketplace_modern_test.js

https://trello.com/c/f7CkP64E/140-js-error-occurs-at-tags-input

Tags: fix js error when fast typing

---

app/views/partials/theme/simple/layout/footer.liquid

Upstream for https://github.com/Platform-OS/pos-community/pull/63

Footer improvements

---

app/views/pages/dashboard/index.liquid
app/views/pages/groups/members.liquid
app/views/partials/theme/simple/groups/show.liquid

https://trello.com/c/LWgk9geT/165-i-can-follow-someone-twice-should-only-follow-a-user-once

Disable double follow

---

app/views/partials/theme/simple/groups/show.liquid

https://trello.com/c/zZqqd9bZ/177-self-follow-bug-through-groups-section

Disable self following in group members page

---

app/views/pages/dashboard/items/create.liquid
app/views/partials/lib/commands/items/create.liquid
app/views/partials/lib/consumers/status_created/update_metrics_cache.liquid
app/views/partials/theme/simple/dashboard/items/index.liquid
test/marketplace_modern_test.js
test/pages/itemsearch.js

Fixes: https://trello.com/c/3VgS8qr8/207-assign-default-status-to-item

Assign default status to item

---

app/views/pages/statuses/create.liquid
app/views/partials/theme/simple/dashboard/orders/actions/buyer.liquid

https://trello.com/c/ktMNOST6/355-pay-manually-method-redirects-to-statuses-instead-of-redirecting-you-to-your-paid-orders-list

Redirect to orders page after pay manualy

---

app/views/pages/admin.html.liquid
app/views/pages/admin/activities/index.liquid
app/views/pages/admin/categories/index.liquid
app/views/pages/admin/items/index.liquid
app/views/pages/admin/orders/index.liquid
app/views/pages/admin/support-tickets/delete.liquid
app/views/pages/admin/support-tickets/index.liquid
app/views/pages/admin/support-tickets/show.liquid
app/views/pages/admin/users/index.liquid
app/views/pages/categories/create.liquid
app/views/pages/categories/delete.liquid
app/views/pages/categories/edit.liquid
app/views/pages/categories/new.liquid
app/views/pages/categories/update.liquid
app/views/pages/marketplace_setup/create.liquid
app/views/pages/marketplace_setup/index.liquid
app/views/partials/lib/must_be_superadmin.liquid

Fixes: https://trello.com/c/wF5UGIYr/195-move-superadmin-logic-from-context-to-profile

Admin: use profile instead of context

---

app/views/partials/theme/simple/home/search_form.liquid
app/views/partials/theme/simple/items/form.liquid

Fixes: https://trello.com/c/jkTOdbUJ/241-unexpected-chars-in-categories

Categories: fix select indentation

---

app/graphql/items/create.graphql
app/graphql/items/search.graphql
app/graphql/items/update.graphql
app/model_schemas/item.yml
app/views/pages/items/show.liquid
app/views/partials/lib/commands/items/update/build.liquid
app/views/partials/link_to.liquid

https://trello.com/c/Z58vWHei/234-store-slug-in-the-database-for-the-items

Store item slug

---

app/translations/en.yml
app/views/pages/comments/create.liquid
app/views/partials/theme/simple/comments/new_entry.liquid

https://trello.com/c/MxqUp0B7/250-when-im-on-my-activity-feed-and-want-to-upload-image-without-any-text-i-get-some-error-with-any-text-it-works-properly
Now you have to enter some text before sending comment.

Comments: require body

---

app/translations/en.yml
app/views/pages/orders/line_items/update.liquid
app/views/partials/theme/simple/dashboard/orders/show.liquid

https://trello.com/c/WvkHU5nA/208-check-if-quantity-is-greater-than-1

Disable empty checkout

---

app/graphql/photos/create.graphql
app/views/pages/api/photos/create.json.liquid
app/views/partials/lib/queries/photos/find.liquid
app/views/partials/theme/simple/dashboard/profile/edit.liquid

Fixes: https://trello.com/c/DxkAG9H0/229-avatar-displayed-in-im

Profile: update session avatar when changed only avatar

---

app/graphql/photos/create.graphql
app/views/pages/api/photos/create.json.liquid
app/views/partials/lib/queries/photos/find.liquid
app/views/partials/theme/simple/dashboard/profile/edit.liquid
src/js/markdown-editor.js

https://trello.com/c/0mebHZvA/263-images-in-posts-are-wrongly-displayed
This is gonna fix only new entries.

Questions use compressed version of uploaded image

---

README.md
src/js/markdown-editor.js

https://trello.com/c/oeAs4Se0/365-uploading-images-for-questions-answers-is-broken

Questions: fix uploading images with whitespace

---

app/views/partials/theme/simple/users/form.liquid
test/marketplace_modern_test.js
test/pages/newsession.js

https://trello.com/c/8GbOHHwr/360-fix-error-layout-on-register-page

Fixed layout and added required props
